"""产出物文案的国际化——**唯一真相源**。

## 适用范围（重要，别用错地方）

**走本模块**：会写进**产出物**的文字——图上绘制的标注、报告正文、JSON 里的
reason / note 文案。这些是用户会截图、贴进 PR、交给同事看的东西，必须能切换语言。

**不走本模块**：**控制台进度输出一律英文**（`print` 直接写英文即可）。
理由：CLI 是英文优先的开发者工具，进度日志（`Loading model...` / `OK (77s)`）
在国际化上收益极低、维护成本极高（上百条），且中文用户读英文日志没有障碍。
同一条规则**不要在两处写**——本段是它的唯一出处。

**永不翻译（locale-neutral）**：圈号 `①②③…`、轴名 `X/Y/Z`、`Δ`、`mm`、`°`、`×`、
方向 tag（如 `-1+1+0`）、以及 `skipped_parts.reason` 这类**机器读的枚举值**
（`timeout` / `too_complex` / `no_shape` / `user_skipped`）。枚举值是契约，翻译它
等于破坏下游解析。

## 为什么要有模块级语言状态

产出物文案是在**深层渲染函数**里生成的（`render_one` / `add_direction_banner`），
把 lang 一路当参数透传会污染十几个函数签名。这里用模块级状态 + 每个脚本入口调一次
`set_lang()`——**每个脚本都是独立进程**（流水线靠子进程调用），所以不存在跨请求污染。
"""
import os

DEFAULT_LANG = "en"

# 环境变量名（AGENTS.md §2 的 `CADDIFF_*` 前缀约定）。
# 存在的理由：Docker / CI 里设一次比每条命令都带 `--lang` 方便得多。
ENV_LANG = "CADDIFF_LANG"

# 语言代码 -> 该语言的文案表。新增语言只需在这里加一份，键必须齐全。
_LANGS = {
    "en": {
        # —— 图上标注（render_diff.py）——
        "banner.view_dir": "View dir (X,Y,Z) = ({x:+.2f}, {y:+.2f}, {z:+.2f})",
        "banner.title.overview": "Overview · view {tag}",
        "banner.title.closeup": "{label} · close-up",
        "banner.title.moved_new": "{label} · new position",
        "banner.title.moved_old": "{label} · old position",
        "label.old": "Old",
        "label.new": "New",
        # —— JSON 产出物（render_diff.py / geom_diff.py）——
        "summary.no_geometry_diff": "No geometric differences detected between the two versions",
        "alignment.no_pairs": "No paired parts; cannot assess global alignment",
        # —— 报告（report.py）——
        "report.title": "Geometry diff report — {old} → {new}",
        "report.summary_line": "{geometry} geometric change(s), {bom} BOM-level change(s)",
        "report.none": "No differences detected between the two versions",
        "report.warn.alignment": ("Global alignment looks inconsistent — many of these "
                                  "differences may be spurious"),
        "report.section.bom": "BOM-level changes",
        "report.section.changes": "Geometric changes",
        "report.section.skipped": "Not compared / not resolved",
        "report.section.settings": "Settings used",
        "report.bom.added": "Parts only in the new version",
        "report.bom.removed": "Parts only in the old version",
        "report.bom.count_mismatch": "Instance count changed",
        "report.type.moved": "moved",
        "report.type.shape_changed": "shape changed",
        "report.field.translation": "Translation",
        "report.field.rotation": "Rotation",
        "report.field.volume_delta": "Volume change",
        "report.field.volume_delta_pct": "Volume change (%)",
        "report.field.removed": "Material removed",
        "report.field.added": "Material added",
        "report.field.clusters": "Separate clusters",
        "report.field.diff_extent": "Changed extent",
        "report.field.view": "Viewpoint",
        "report.view.internal": "inside the assembly — located by the red box only",
        "report.panel.overview_rect": "Overview",
        "report.panel.closeup_old_rect": "Old version, close-up",
        "report.panel.closeup_new_rect": "New version, close-up",
        "report.skipped.reason.user_skipped": "skipped on request (--skip-parts)",
        "report.skipped.reason.no_shape": "no solid shape to compare",
        "report.skipped.reason.too_complex": "too many faces for a boolean operation",
        "report.skipped.reason.timeout": "boolean operation timed out",
        "report.skipped.reason.brep_export_failed": "BREP export for the boolean worker failed",
        "report.skipped.reason.worker_crashed": "the boolean worker crashed",
        "report.skipped.reason.worker_failed": "the boolean worker failed",
        "report.skipped.reason.assembly_container": (
            "assembly container — its shape is the union of its children, so it is not "
            "counted separately"),
        "report.skipped.reason.other": "not compared",
        "report.filtered": ("filtered out — {pct}% change is below the "
                            "{threshold}% threshold"),
        "report.footer": "Generated by caddiff · manifest version {version}",
    },
    "zh": {
        "banner.view_dir": "视线方向 (X, Y, Z) = ({x:+.2f}, {y:+.2f}, {z:+.2f})",
        "banner.title.overview": "整体定位  视角 {tag}",
        "banner.title.closeup": "{label}  特写",
        "banner.title.moved_new": "{label}  新位置",
        "banner.title.moved_old": "{label}  旧位置",
        "label.old": "旧版",
        "label.new": "新版",
        "summary.no_geometry_diff": "两版之间未检出几何差异",
        "alignment.no_pairs": "无已配对零件，无法判断整体配准",
        "report.title": "几何差异报告 — {old} → {new}",
        "report.summary_line": "{geometry} 处几何变化，{bom} 处 BOM 层变化",
        "report.none": "两版之间未检出差异",
        "report.warn.alignment": "两版整体配准疑似不一致，其中不少差异可能是伪差异",
        "report.section.bom": "BOM 层变化",
        "report.section.changes": "几何变化",
        "report.section.skipped": "未参与比对 / 未解析",
        "report.section.settings": "本次使用的参数",
        "report.bom.added": "仅新版有的零件",
        "report.bom.removed": "仅旧版有的零件",
        "report.bom.count_mismatch": "实例数量发生变化",
        "report.type.moved": "位置变化",
        "report.type.shape_changed": "形状变化",
        "report.field.translation": "位移量",
        "report.field.rotation": "旋转量",
        "report.field.volume_delta": "体积变化",
        "report.field.volume_delta_pct": "体积变化（百分比）",
        "report.field.removed": "减少材料",
        "report.field.added": "新增材料",
        "report.field.clusters": "差异簇数量",
        "report.field.diff_extent": "差异范围",
        "report.field.view": "视角",
        "report.view.internal": "位于装配体内部——仅以红框定位",
        "report.panel.overview_rect": "整体定位",
        "report.panel.closeup_old_rect": "旧版特写",
        "report.panel.closeup_new_rect": "新版特写",
        "report.skipped.reason.user_skipped": "按调用方要求跳过（--skip-parts）",
        "report.skipped.reason.no_shape": "没有可比的实体形状",
        "report.skipped.reason.too_complex": "面数超过布尔运算闸门",
        "report.skipped.reason.timeout": "布尔运算超时",
        "report.skipped.reason.brep_export_failed": "为布尔子进程导出 BREP 失败",
        "report.skipped.reason.worker_crashed": "布尔子进程崩溃",
        "report.skipped.reason.worker_failed": "布尔子进程执行失败",
        "report.skipped.reason.assembly_container": "装配体容器——其形状是全部子件的并集，不单独计数",
        "report.skipped.reason.other": "未参与比对",
        "report.filtered": "被筛除——体积变化 {pct}% 低于 {threshold}% 阈值",
        "report.footer": "由 caddiff 生成 · manifest 版本 {version}",
    },
}

_current = DEFAULT_LANG


def available_langs():
    """返回支持的语言代码列表（供 CLI 的 --lang 选项生成 choices）。"""
    return sorted(_LANGS)


def normalize_lang(lang):
    """把用户输入归一成受支持的语言代码。

    支持 `zh` / `zh-CN` / `zh_CN` / `en-US` 这类写法——用户不该因为多写了个地区码
    就被拒绝。认不出来时回退到默认语言（**不抛错**：语言不该让一次 6 分钟的渲染失败）。
    """
    if not lang:
        # 环境变量兜底：调用方没显式指定语言时才看它（显式参数优先）。
        lang = os.environ.get(ENV_LANG)
    if not lang:
        return DEFAULT_LANG
    code = str(lang).strip().lower().replace("_", "-")
    if code in _LANGS:
        return code
    base = code.split("-")[0]
    return base if base in _LANGS else DEFAULT_LANG


def set_lang(lang):
    """设置当前进程的产出物语言，返回归一化后的语言代码。"""
    global _current
    _current = normalize_lang(lang)
    return _current


def get_lang():
    return _current


def t(key, **kwargs):
    """取文案并做 ``str.format`` 插值。

    键在当前语言缺失时**回退到默认语言**，再缺失就**原样返回 key**——这样缺翻译会
    在产出物里显式暴露成 `banner.title.overview` 这种字符串，一眼能看出漏了哪条，
    比静默返回空串好排查。
    """
    table = _LANGS.get(_current, _LANGS[DEFAULT_LANG])
    text = table.get(key)
    if text is None:
        text = _LANGS[DEFAULT_LANG].get(key, key)
    if kwargs:
        try:
            return text.format(**kwargs)
        except (KeyError, IndexError, ValueError):
            # 占位符对不上时不要把渲染整挂掉：返回未插值原文，缺什么一眼可见
            return text
    return text


# ===== PPTX 文案（由 build_pptx.py 使用）=====
# 单独成节：PPT 是可选的次要导出路径（AGENTS.md §11 D-006），文案量大（数十条），
# 与图上标注 / JSON 的键分开更好维护。
#
# 【为什么在文件末尾合并、而不是写进上面 _LANGS 的字面量块】
# `t()` 是在**调用时**才去查 `_LANGS` 的（见 `t()` 的函数体），而本段代码在**模块导入时**
# 就执行完毕，一定早于任何一次 `t(...)` 调用。所以合并后的 pptx.* 键对 `t()` 完全可见，
# 这样写是有效的，不是"导入后就没用了"。反过来，**不要**把这些键再抄一份到上面的
# `_LANGS` 字面量块里——两处维护必然漂移。
#
# 【空白约定】中文用全角括号/冒号（自带间距），英文用半角（需要额外空格），
# 故少数键的译文带首/尾空格（如 pptx.skipped.faces、pptx.warn.alignment_label），
# 它们是刻意为之的排版分隔，不是笔误。
#
# 【图例必须一行放得下】pptx.legend.* 的英文比中文宽，改长前先按 docs/pipeline.md 坑 G7
# 重新量一遍——图例行只有 LEGEND_H 一行高度，换行会被裁掉。
_PPTX_KEYS = {
    "en": {
        # —— 汇总表表头（build_pptx.summary_col_labels()）——
        "pptx.col.index": "No.",
        "pptx.col.part_name": "Part name",
        "pptx.col.type": "Type",
        "pptx.col.volume_delta": "Volume change (mm³)",
        "pptx.col.share": "Share (%)",
        "pptx.col.diff_size": "Diff region size (mm)",
        "pptx.col.detail_page": "Detail slide",
        # —— 字段标签 ——
        "pptx.field.diff_region_size": "Diff region size",
        "pptx.field.candidates": "Candidate parts",
        "pptx.field.conclusion": "Conclusion",
        "pptx.field.alignment_warning": "Global alignment warning",
        "pptx.field.translation": "Shift distance",
        "pptx.field.rotation": "Rotation",
        "pptx.field.part_volume": "Part volume",
        "pptx.field.removed_material": "Material removed",
        "pptx.field.added_material": "Material added",
        "pptx.field.change_note": "What changed",
        "pptx.field.overview_view": "Overview view",
        # —— 类型 / 角色 / 取值 ——
        "pptx.change_type.moved": "Moved",
        "pptx.change_type.shape": "Shape",
        "pptx.role.added": "Added",
        "pptx.role.removed": "Removed",
        "pptx.value.cluster_count": "{n} regions",
        "pptx.value.rotation_none": "None (translation only)",
        "pptx.value.rotation_bbox_note": " (inferred from bbox ordering, low confidence)",
        # —— 无差异页 ——
        "pptx.empty.title": "No geometric differences detected",
        "pptx.empty.skipped_header": "Parts not compared / needing manual review",
        "pptx.skipped.reason": "Reason: {reason}",
        "pptx.skipped.faces": " ({n} faces)",
        "pptx.filtered.below_threshold": "Diff {delta} mm³ ({pct}%) below the relative threshold {threshold}% — filtered out",
        # —— 汇总页 ——
        "pptx.summary.title": "Difference summary  {old} → {new}",
        "pptx.summary.stats": "{count} differences  |  {candidates} candidate parts compared",
        "pptx.summary.limited": "⚠ Detail slides cover only the top {limit} (by importance); the rest are listed above",
        "pptx.warn.header": "The following parts were not compared or need manual review",
        "pptx.warn.alignment_label": "Global alignment warning: ",
        "pptx.warn.item": "{name}: {reason}",
        "pptx.warn.filtered": "{name}: diff {delta} mm³ ({pct}%) below the threshold — filtered out",
        # 汇总页警告区每条只有 280000 EMU 高度（10pt 约 2 行），英文比中文宽：
        # 实测长式（"...the two versions may use different global datums; please verify
        # manually"）会折成两行、把下一条挤到紧贴。故英文取短式，中文保持原文。
        "pptx.alignment.warning": "Median shift of paired parts {median} mm, direction consistency {consistency} — possible global datum change; verify manually",
        # —— 详情页标题条 ——
        "pptx.title.counter": "Diff {index} / {total}",
        "pptx.title.delta": "Change",
        # 标题条第 2 行只有 content_w*0.55 宽，英文比中文宽得多：实测
        # "Assembly position / pose change" + "(identical in both versions)" 会折成两行，
        # 末行压到图区上（PowerPoint 导出图确认）。故英文取短式，中文保持原文。
        "pptx.title.pose_change": "Position / pose change",
        "pptx.title.volume_unchanged": "{volume} mm³ (identical in both)",
        # —— 详情页右栏 ——
        "pptx.desc.moved": "Geometry unchanged; only the assembly position / pose changed. Magenta = the moved part body; the blue arrow on the new-position image points from the old position to the new one.",
        "pptx.desc.no_magenta": "No magenta in this image (the difference is purely added or removed material — it exists in only one version)",
        "pptx.note.view_fallback": "  · Inside the assembly, occluded from every direction — located by the red box only",
        "pptx.note.view_auto": "  · Auto-selected: least occluded, clearest view",
        # —— 图例 ——
        "pptx.legend.label": "Legend",
        "pptx.legend.moved_magenta": "Magenta = the moved part body (old left, new centre)",
        "pptx.legend.moved_arrow": "Blue arrow = old → new position, with the shift",
        "pptx.legend.axes_moved": "Banner arrow = world axes (X red / Y green / Z blue)",
        "pptx.legend.shape_magenta": "Magenta = material changed here (removed old, added new)",
        "pptx.legend.shape_redbox": "Red box = diff regions; ①② match the left column",
        "pptx.legend.axes_shape": "Banner arrow = world axes (X red / Y green / Z blue)",
    },
    "zh": {
        # —— 汇总表表头（build_pptx.summary_col_labels()）——
        "pptx.col.index": "序号",
        "pptx.col.part_name": "零件名",
        "pptx.col.type": "类型",
        "pptx.col.volume_delta": "体积变化(mm³)",
        "pptx.col.share": "占比(%)",
        "pptx.col.diff_size": "差异区域尺寸(mm)",
        "pptx.col.detail_page": "详情页",
        # —— 字段标签 ——
        "pptx.field.diff_region_size": "差异区域尺寸",
        "pptx.field.candidates": "比对候选零件数",
        "pptx.field.conclusion": "结论",
        "pptx.field.alignment_warning": "整体配准告警",
        "pptx.field.translation": "位移量",
        "pptx.field.rotation": "旋转角",
        "pptx.field.part_volume": "零件体积",
        "pptx.field.removed_material": "减少材料",
        "pptx.field.added_material": "新增材料",
        "pptx.field.change_note": "变化说明",
        "pptx.field.overview_view": "整体图视角",
        # —— 类型 / 角色 / 取值 ——
        "pptx.change_type.moved": "位移",
        "pptx.change_type.shape": "形状",
        "pptx.role.added": "增料",
        "pptx.role.removed": "减料",
        "pptx.value.cluster_count": "共 {n} 处",
        "pptx.value.rotation_none": "无（仅平移）",
        "pptx.value.rotation_bbox_note": "（由 bbox 排列推断，置信度较低）",
        # —— 无差异页 ——
        "pptx.empty.title": "未检出几何差异",
        "pptx.empty.skipped_header": "未参与比对 / 需人工复核的零件",
        "pptx.skipped.reason": "原因：{reason}",
        "pptx.skipped.faces": "（面数 {n}）",
        "pptx.filtered.below_threshold": "差异 {delta} mm³ ({pct}%) 低于相对阈值 {threshold}%，已筛除",
        # —— 汇总页 ——
        "pptx.summary.title": "差异汇总  {old} → {new}",
        "pptx.summary.stats": "共 {count} 处差异  |  比对候选零件 {candidates} 个",
        "pptx.summary.limited": "⚠ 详情页仅覆盖前 {limit} 处（按重要度），其余见上表",
        "pptx.warn.header": "以下零件未参与比对或需要人工复核",
        "pptx.warn.alignment_label": "整体配准告警：",
        "pptx.warn.item": "{name}：{reason}",
        "pptx.warn.filtered": "{name}：差异 {delta} mm³ ({pct}%) 低于阈值，已筛除",
        "pptx.alignment.warning": "已配对零件位移中位数 {median} mm、方向一致性 {consistency}，疑似两版整体基准变更，请人工确认",
        # —— 详情页标题条 ——
        "pptx.title.counter": "差异 {index} / {total}",
        "pptx.title.delta": "变化量",
        "pptx.title.pose_change": "装配位置 / 姿态变化",
        "pptx.title.volume_unchanged": "{volume} mm³（两版相同）",
        # —— 详情页右栏 ——
        "pptx.desc.moved": "该零件几何未变，仅装配位置 / 姿态改变。品红＝发生位移的零件本体，新位置图上的蓝色箭头由旧位置指向新位置。",
        "pptx.desc.no_magenta": "此图无品红（该差异为纯增料或纯减料，材料只存在于另一版本）",
        "pptx.note.view_fallback": "  · 该差异位于装配体内部，各向均被遮挡，故仅以红框定位",
        "pptx.note.view_auto": "  · 自动选取，以差异最不被遮挡且画面清晰为准",
        # —— 图例 ——
        "pptx.legend.label": "图例",
        "pptx.legend.moved_magenta": "品红＝发生位移的零件本体（左图旧位置，中图新位置）",
        "pptx.legend.moved_arrow": "蓝箭头＝由旧位置指向新位置，旁标位移量",
        "pptx.legend.axes_moved": "标记带内箭头＝世界坐标轴方向（X红 / Y绿 / Z蓝）",
        "pptx.legend.shape_magenta": "品红＝本次改动的材料（旧版图为被去掉的，新版图为新增的）",
        "pptx.legend.shape_redbox": "红框＝各处差异分别定位，①②对应左栏清单",
        "pptx.legend.axes_shape": "各图顶部标记带内箭头＝该视角下的世界坐标轴方向（X红 / Y绿 / Z蓝）",
    },
}

for _code, _table in _PPTX_KEYS.items():
    _LANGS.setdefault(_code, {}).update(_table)
